spring:
  application: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**

            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/recommendations/**

            - id: activity-service
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/api/activities/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak-production-53c1.up.railway.app/realms/fitness-app/protocol/openid-connect/certs
eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: false
#    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
