spring:
  datasource:
    url: jdbc:postgresql://user-service-student-c7ce.j.aivencloud.com:10745/userdb
    username: avnadmin
    password: AVNS_cwbFvkJGWYrR4zOvv9d
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081